rust-toolchain.toml

[toolchain]
channel = "1.78.2"
components = ["rustfmt","clippy","cargo","rust-src","rust-analyzer"]
targets=["x86_64-unknown-linux-gnu","aarch64-unknown-linux-gnu","x86_64-pc-windows-msvc","x86_64-apple-darwin","wasm32-unknown-unknown"]
profile="minimal"
rustflags=["-C","opt-level=3","-C","target-cpu=native","-D","warnings","-C","lto=fat"]

[override]
# CeloHT workspace
